import Head from 'next/head'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {
  // Request data to the backend
  const req = await fetch('https://localhost:7069/Blog', {
    method: 'GET'
  })

  const blogPosts = await req.json()

  return {
    props: {
      posts: blogPosts
    }
  }
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Blog with CoreAdmin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {posts.map((post) => (
            <a key={post.id} href={post.slug} className={styles.card}>
              <h2>{post.title} &rarr;</h2>
              <p>At {new Date(post.created).toLocaleString()}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}